In [1]:
import torch
import numpy as np
import time
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print(device)


cuda


In [2]:
%%time

start_time = time.time()
zeros = torch.zeros(1,1)
end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.4f}')

0.0127
CPU times: total: 0 ns
Wall time: 12.7 ms


In [3]:
%%time

torch_rand1 = torch.rand(100,100,100,100).to(device)
torch_rand2 = torch.rand(100,100,100,100).to(device)

np_rand1 = torch.rand(100,100,100,100)
np_rand2 = torch.rand(100,100,100,100)

start_time = time.time()

rand = (torch_rand1 @ torch_rand2)

end_time = time.time()

elapsed_time = end_time - start_time
print(f'{elapsed_time:.8f}')

start_time = time.time()

rand = np.multiply(np_rand1,np_rand2)

end_time = time.time()
elapsed_time = end_time - start_time

print(f'{elapsed_time:.8f}')

4.58289170
2.11323619
CPU times: total: 4.31 s
Wall time: 10.9 s


In [4]:
probablities = torch.tensor([0.1, 0.9])

samples = torch.multinomial(probablities, num_samples = 10, replacement = True)
print(samples)

tensor([1, 1, 1, 1, 1, 1, 0, 1, 1, 0])


In [5]:
tensor = torch.tensor([1,2,3,4])
out = torch.cat((tensor, torch.tensor([5])), dim = 0)
out

tensor([1, 2, 3, 4, 5])

In [6]:
out = torch.tril(torch.ones(4,4))
out

tensor([[1., 0., 0., 0.],
        [1., 1., 0., 0.],
        [1., 1., 1., 0.],
        [1., 1., 1., 1.]])

In [7]:
input = torch.zeros(2,3,4)
print(input)
print(input.shape)
out = input.transpose(0,2)

print(out.shape)
print(out)

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])
torch.Size([2, 3, 4])
torch.Size([4, 3, 2])
tensor([[[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.],
         [0., 0.]]])


In [8]:
#stacking tensors

tensor1 = torch.tensor([1,2,3,4])
tensor2 = torch.tensor([5,6,7,8])
tensor3 = torch.tensor([1,2,3,4])

stacked_tensor = torch.stack([tensor1, tensor2 , tensor3])
stacked_tensor

tensor([[1, 2, 3, 4],
        [5, 6, 7, 8],
        [1, 2, 3, 4]])

In [9]:
import torch.nn as nn
sample = torch.tensor([10.,10.,10.,10.])
linear = nn.Linear(4,4, bias = False)
# Linear(out_features, in_features) They both have to be of the same size except the last dimension.
print(linear(sample))

tensor([  4.0423,   1.6244, -10.1413,   6.1505], grad_fn=<SqueezeBackward4>)


In [10]:
import torch.nn.functional as f

tensor1 = torch.tensor([1.0,2.0,3.0])

softmax_output = f.softmax(tensor1, dim = 0)

print(softmax_output)

tensor([0.0900, 0.2447, 0.6652])


In [12]:
import torch
import torch.nn as nn

# Define the vocabulary size and embedding dimension
vocab_size = 10  # Number of unique items in the vocabulary
embedding_dim = 4  # Dimensionality of the embedding vectors

# Create an instance of nn.Embedding
embedding_layer = nn.Embedding(num_embeddings=vocab_size, embedding_dim=embedding_dim)

# Define some input indices (representing items or words)
input_indices = torch.tensor([1, 5, 7, 2, 0])

# Perform a lookup in the embedding layer
embedded_vectors = embedding_layer(input_indices)

# Print the resulting embedded vectors
print(embedded_vectors.shape)

print(embedded_vectors)


torch.Size([5, 4])
tensor([[-0.5243, -0.7070,  0.9727,  1.1905],
        [ 0.3307,  0.8113,  0.4419,  0.4627],
        [-0.2878,  1.2626,  1.0276, -0.6417],
        [-2.3185,  0.2230, -1.0698, -1.1936],
        [-1.9819,  0.2049, -0.3577,  0.5450]], grad_fn=<EmbeddingBackward0>)


In [20]:
int_64 = torch.rand((3,2))
print(int_64)
float_32 = torch.rand(2,3)
print(float_32)
result = (int_64 @ float_32)
print(result)


tensor([[0.1465, 0.8193],
        [0.6933, 0.0363],
        [0.7762, 0.8313]])
tensor([[0.7495, 0.5705, 0.5688],
        [0.0758, 0.5918, 0.6840]])
tensor([[0.1719, 0.5685, 0.6437],
        [0.5224, 0.4170, 0.4191],
        [0.6448, 0.9348, 1.0101]])
